[package]
name = "ai_chess"
version = "0.1.0"
authors = ["CadenMG <cadengarrett@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess = "3.2.0"